### PR TITLE
Add vim-cdo.

### PR DESCRIPTION
**Pull request by amygimma**
- Refactor across the whole repo with ease.

### CODE REVIEW

**Comment by mwenger1** [comment]
:ship:

**Comment by arktisklada** [comment]
:ship: could you provide an example of how this could be used and it's benefits?

**Comment by mwenger1** [comment]
@arktisklada It's really helpful for search and replace all across multiple files.

Basically do:
`grep search-term`

Then you can do either:
`Cn` to go to the next grep item.

OR

`Cdo s/search-term/new-term/gc` and it will allow you to confirm text changes across multiple files

**Comment by arktisklada** [comment]
:+1: awesome! Thanks @mwenger1 for the examples

**Comment by christopher-haueter** [comment]
@arktisklada here's an asciicast I just created, showing :Cdo in action. https://asciinema.org/a/bkk203ogi8i8uai2oz1wsib47

**Pull request merged**
