### PR TITLE
Enable tmux wheel scroll!! OMGGGGzor!!!!!!1111! so happy

### PR DESCRIPTION
**Pull request by christopher-haueter**

### CODE REVIEW

**Comment by hannahhearth** [comment]
:beers:

**Comment by christopher-haueter** [comment]
Source: http://superuser.com/questions/210125/scroll-shell-output-with-mouse-in-tmux

**Comment by mwenger1** [comment]
Boo using the mouse :-1:

**Comment by mwenger1** [comment]
But really :100:

**Comment by christopher-haueter** [comment]
Let's keep this a safe space, @mwenger1 :trollface: :stuck_out_tongue_winking_eye:

**Comment by hannahhearth** [comment]
@chrishaum are you getting this error: 

`/Users/hoppenheimer/.tmux.conf:65: unknown option: mode-mouse`

**Pull request merged**
