### PR TITLE
Add grecent alias. Show 10 most recently used branches

### PR DESCRIPTION
**Pull request by christopher-haueter**
cc @mwenger1 whose alias this is

### CODE REVIEW

**Comment by chrishaum** [comment]
cc @mwenger1 test

**Comment by chrishaum** [comment]
cc foo

**Comment by arktisklada** [comment]
Why limit it to 10 branches?  Chances are if there are more than that, someone isn't properly deleting their branches after removing, OR they're working on too many things and creating a branch mess

**Comment by arktisklada** [comment]
Actually, that reminds me... https://github.com/EpionHealth/dotfiles/pull/41

**Comment by mwenger1** [comment]
@arktisklada 👍 on removing the count

**Pull request merged**
