### PR TITLE
aliases for tmux commands

### PR DESCRIPTION
**Pull request by hannahhearth**

### CODE REVIEW

**Comment by mwenger1** [comment]
@opihana do you still need to add the `-t` ?

So in practice this would be:
`ta -t 0`  ?

**Comment by hannahhearth** [comment]
@mwenger1 fixed!

**Comment by mwenger1** [comment]
:ship:

**Comment by christopher-haueter** [comment]
:ship:

**Comment by mwenger1** [comment]
@opihana Can you merge this in

**Comment by christopher-haueter** [comment]
@mwenger1 @opihana looks like this was merged into master 12 days ago: https://github.com/EpionHealth/dotfiles/commit/198e84674bc05f675718bb08404e33c22356e9d1

Closing this PR.

**Pull request closed without merging**
