### PR TITLE
:AV auto-creates empty spec file (except .rake)

### PR DESCRIPTION
**Pull request by arktisklada**
https://trello.com/c/ZZQiQVxd

### CODE REVIEW

**Comment by mwenger1** [comment]
:+1:

**Comment by christopher-haueter** [comment]
@arktisklada in https://github.com/EpionHealth/vim-rails/commit/ed0bc274efc04f83f9e98ee056787ec72dffc2c6, WDUT about deleting the relevant code instead of commenting it out?

**Comment by arktisklada** [comment]
@chrishaum i wanted to try and get it work, but deleting it makes sense for now.  No need for WIP in our used code

**Comment by christopher-haueter** [comment]
:+1: on deleting it

**Pull request merged**
